<?xml version="1.0"?>
<robot name="mobile_robot_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

<!-- *********************************************************************** -->

<xacro:include filename="$(find mobile_robot_base_ros1)/urdf/common_macro.xacro" />

<!-- *********************************************************************** -->

<xacro:macro 
    name="camera" 
    params="
        link_name  
        length
        width
        height
        mass">
        <link name="${link_name}">
            <visual>
                <origin 
                    rpy= "0 0 0"
                    xyz= "0 0 ${height/2}"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
                <material name="yellow">
                    <color rgba="1 1 0 1"/>
                  </material>
            </visual>
            <collision>
                <origin 
                    rpy= "0 0 0"
                    xyz= "0 0 ${height/2}"/>
                <geometry>
                    <box size="${length} ${width} ${height}"/>
                </geometry>
            </collision>
            <xacro:inertial_matrix mass="${mass}"/>
        </link>
        <gazebo reference ="${link_name}">
            <material>Gazebo/Yellow</material>
            <sensor type="camera" name="camera_1">
                <update_rate>30.0</update_rate>
                <camera name="camera">
                  <horizontal_fov>1.3962634</horizontal_fov>
                  <image>
                    <width>400</width>
                    <height>400</height>
                    <format>R8G8B8</format>
                  </image>
                  <clip>
                    <near>0.02</near>
                    <far>300</far>
                  </clip>
                  <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.007</stddev>
                  </noise>
                </camera>
                <plugin name="camera_controller" filename="libgazebo_ros_camera.so">
                  <alwaysOn>true</alwaysOn>
                  <updateRate>0.0</updateRate>
                  <cameraName>camera</cameraName>
                  <imageTopicName>image_raw</imageTopicName>
                  <cameraInfoTopicName>camera_info</cameraInfoTopicName>
                  <frameName>camera_link</frameName>
                  <hackBaseline>0.07</hackBaseline>
                  <distortionK1>0.0</distortionK1>
                  <distortionK2>0.0</distortionK2>
                  <distortionK3>0.0</distortionK3>
                  <distortionT1>0.0</distortionT1>
                  <distortionT2>0.0</distortionT2>
                </plugin>
              </sensor>
          </gazebo>
</xacro:macro>
</robot>
